# Generated by Django 4.1.7 on 2023-03-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0002_alter_menu_options_alter_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='default', max_length=255, unique=True, verbose_name='Menu name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='treemenu.menu'),
        ),
    ]
