# Generated by Django 4.1.7 on 2023-03-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0003_menu_name_alter_category_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Меню категории', 'verbose_name_plural': 'Меню категорий'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
