# Generated by Django 4.1.7 on 2023-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0004_alter_category_options_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Menu category', 'verbose_name_plural': 'Menu categorys'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
