# Generated by Django 4.1.7 on 2023-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0006_alter_category_options_alter_menu_options_menu_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='slug'),
        ),
    ]
